---
title: "Full Code Bachelor Thesis"
author: "JonasSchernich"
date: "2023-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(csranks)
library(lubridate)
library(sandwich)
library(lmtest)
library(car)
library(stats)
library(ggplot2)
library(matrixStats)
library(gridExtra)
```

```{r Portfolios since 1970}
# setwd("/Users/jonasschernich/Uni/6. Semester/Bachelorarbeit/InferenceForRanks")
#Reading the data
Nikkei70 <- read.csv2("Nikkei.csv")[-c(1:5218),]
indices70 <- cbind(read.csv2("Indizes.csv")[-1, c(1, 2, 11, 12, 16)], Nikkei70$NIKKEI.225.STOCK.AVERAGE...PRICE.INDEX)
gold <- read.csv2("Gold.csv")
indices70$gold <- na.omit(gold)[-c(1:521),2]
colnames(indices70) <- c("date", "World", "SP500", "DAX", "HANGSENG", "Nikkei", "Gold")
indices70$date <- as.Date(strptime(indices70$date, format = "%d.%m.%y"))


indices70$SP500 <- as.numeric(gsub(",", ".", indices70$SP500))
indices70$DAX <- as.numeric(gsub(",", ".", indices70$DAX))
indices70$HANGSENG <- as.numeric(gsub(",", ".", indices70$HANGSENG)) 


# normalizing 
for(i in 2 : ncol(indices70)) {
  indices70[i] <- indices70[i] / indices70[1, i] * 100
}


#Setting up the S&P 500 leveraged portfolios
SP <- indices70[c(1,3)]
sp_value <- indices70$SP500
SPmoving_avrg <- rep(TRUE, length(sp_value))
# Calculating S&P 200day moving average dates
for(i in 201 : length(sp_value)) {
  if(sp_value[i] < mean(sp_value[(i - 200):(i - 1)])) {
    SPmoving_avrg[i] <- FALSE
  }
}
# Initialize empty vectors
under <- c()
over <- c()

# Identify positions of first FALSE after TRUE and first TRUE after FALSE
for (i in 2 : length(SPmoving_avrg)) {
  if (SPmoving_avrg[i] == FALSE && SPmoving_avrg[i-1] == TRUE) {
    under <- c(under, i)
  }
  if (SPmoving_avrg[i] == TRUE && SPmoving_avrg[i-1] == FALSE) {
    over <- c(over, i)
  }
}

SP_return <- SP
cSP <- SP
for(i in 1 : nrow(SP)) {
  SP_return$SP500[i] <- (SP$SP500[i+ 1] - SP$SP500[i])/SP$SP500[i]
}
SP_return <- SP_return[-nrow(SP_return),]
SP_return$return3x <- SP_return$SP500 * 3

#### Gold under 200sma
gold$return <- c(rep(0, length(gold$X.NAME.)))
# calculating returns for gold
for(i in 2 : nrow(gold)) {
  gold$return[i] <- (gold$Gold.Bullion.LBM...t.oz.DELAY[i+ 1] - gold$Gold.Bullion.LBM...t.oz.DELAY[i])/gold$Gold.Bullion.LBM...t.oz.DELAY[i]
}
#adapting length of gold
gold_1970 <- gold[-c(1 : 5216, nrow(gold)),]
for(i in 1 : length(over)) {
  SP_return$return3x[under[i]:over[i]] <- gold_1970$return[under[i] : over[i]]
}
SP_return$return3x[under[length(under)] : nrow(SP_return)] <- gold_1970$return[under[length(under)]:nrow(SP_return)]

# adding the 3x leverage
SP_return<- SP_return[-1,]
SP <- rep(100, nrow(SP_return) + 1)
SP3x <- rep(100, nrow(SP_return) + 1)
for(i in 1:(nrow(SP_return))) {
  SP[i + 1] <- SP[i] * (1 + SP_return$SP500[i])
  SP3x[i + 1] <- SP3x[i] * (1 + SP_return$return3x[i])
}
indices70$SP3xLev <- c(100, SP3x)

#### Cash under 200sma
cSP_return <- cSP

for(i in 1:nrow(cSP)) {
  cSP_return$SP500[i] <- (cSP$SP500[i+ 1] - cSP$SP500[i])/cSP$SP500[i]
}
cSP_return <- cSP_return[-nrow(cSP_return),]
cSP_return$return3x <- cSP_return$SP500*3
# adapting gold length
for(i in 1:length(over)) {
  cSP_return$return3x[under[i]:over[i]] <- 0
}
cSP_return$return3x[under[length(under)]:nrow(cSP_return)] <-0

# adding the 3x leverage
cSP_return <- cSP_return[-1,]
cSP <- rep(100, nrow(cSP_return) + 1)
cSP3x <- rep(100, nrow(cSP_return) + 1)
for(i in 1:(nrow(cSP_return))) {
  cSP[i + 1] <- cSP[i] * (1 + cSP_return$SP500[i])
  cSP3x[i + 1] <- cSP3x[i] * (1 + cSP_return$return3x[i])
}
indices70$cSP3xLev <- c(100, cSP3x)


indices70first <- indices70[1,]
indices70first$date <- indices70first$date - 1
indices70 <- rbind(indices70first, indices70)
indices70$Year <- as.numeric(format(indices70$date, "%Y"))
indices70$Month <- as.numeric(format(indices70$date, "%m"))
# Calculating yearly Returns
yearlast <- indices70[!duplicated(indices70$Year, fromLast = TRUE), ]
YearlyReturns1970 <- yearlast
for(i in 2 : 9) {
  for(j in 2 : nrow(yearlast)) {
    YearlyReturns1970[j, i] <- (yearlast[j, i] -  yearlast[j - 1, i])/yearlast[j - 1,i]
  }
}
YearlyReturns1970 <- YearlyReturns1970[-1,-c(10:11)]
YearlyReturns1970$date <- 1970:2022
colnames(YearlyReturns1970)[1] <- "Year"




# calculating monthly returns
monthlast <- indices70 %>%
  group_by(Year, Month) %>%
  filter(date == max(date)) %>%
  ungroup()

MonthlyReturns1970 <- monthlast
for(i in 2 : 9) {
  for(j in 2 : nrow(monthlast)) {
    MonthlyReturns1970[j, i] <- (monthlast[j, i] -  monthlast[j - 1, i])/monthlast[j - 1,i]
  }
}

MonthlyReturns1970 <- MonthlyReturns1970[-1, -c(10:11)]
MonthlyReturns1970$date <- c(1:nrow(MonthlyReturns1970))
colnames(MonthlyReturns1970)[1] <- "Month"

# calculating weekly returns
weeklast <- indices70[seq(1, nrow(indices70), by = 5), ]
WeeklyReturns1970 <- weeklast
for(i in 2 : 9) {
  for(j in 2 : nrow(WeeklyReturns1970)) {
    WeeklyReturns1970[j, i] <- (weeklast[j, i] -  weeklast[j - 1, i])/weeklast[j - 1,i]
  }
}

WeeklyReturns1970 <- WeeklyReturns1970[-1, -c(10:11)]
WeeklyReturns1970$date <- c(1:nrow(WeeklyReturns1970))
colnames(WeeklyReturns1970)[1] <- "Week"
```

```{r Low Beta}
# reading and organizing the data
cola <- read.csv2("KO.csv")
duke <- read.csv2("duk.csv")
ed <- read.csv2("ed.csv")
jnj <- read.csv2("jnj.csv")
kmb <- read.csv2("kmb.csv")
mcd <- read.csv2("mcd.csv")
pep <- read.csv2("pep.csv")
pg <- read.csv2("pg.csv")
vz <- read.csv2("vz.csv")
wmt <- read.csv2("wmt.csv")

SP500 <- data.frame(date = indices70$date[4697:length(indices70$SP500)], Kurs = indices70$SP500[4697:length(indices70$SP500)])



stocks <- list(Cola = cola, Duke = duke, Edison = ed, JnJ = jnj, Clark = kmb, McDonalds=mcd, Pepsi=pep, Procter=pg, Verizon=vz, Walmart=wmt)
# fixing stock data frames and standardizing 
for(i in 1:length(stocks)) {
  stocks[[i]] <- data.frame(
    date = sub(",.*", "", stocks[[i]]$Date.Open.High.Low.Close.Adj.Close.Volume),
    kurs = sub(".*,(.*),(.*),(.*),(.*),.*", "\\2", stocks[[i]]$Date.Open.High.Low.Close.Adj.Close.Volume),
    stringsAsFactors = FALSE)
  stocks[[i]]$kurs <- as.numeric(stocks[[i]]$kurs)
  stocks[[i]]$kurs <- stocks[[i]]$kurs / stocks[[i]][1,2]
  stocks[[i]]$kurs <- stocks[[i]]$kurs * 10
}

lowBetaPortfolio <- stocks[[1]]
for(i in 2:10) {
  lowBetaPortfolio$kurs <- lowBetaPortfolio$kurs + stocks[[i]]$kurs
}
# stopping at end of 2022
lowBetaPortfolio <- lowBetaPortfolio[1:8821,]




#adapting dates of trading days
SP500overlap <- c(2, 33, 67, 108, 133, 178, 236, 258, 263, 298, 322, 368, 394, 438, 496, 518, 523, 558, 597, 628, 655, 698, 756, 779, 784, 818, 847, 888, 916, 958, 1021, 1040, 1045, 1078, 1122, 1148, 1177, 1223, 1281, 1302, 1307, 1338, 1377, 1413, 1438, 1483, 1541, 1562, 1603, 1632, 1650, 1673, 1698, 1743, 1801, 1823, 1828, 1863, 1902, 1933, 1959, 2003, 2061, 2083, 2088, 2123, 2157, 2193, 2221, 2263, 2326, 2345, 2350, 2383, 2412, 2453, 2482, 2523, 2586, 2606, 2611, 2623, 2643, 2682, 2713, 2742, 2788, 2846, 2867, 2872, 2883, 2903, 2937, 2978, 3003, 3048, 3106, 3127, 3143, 3168, 3212, 3238, 3264, 3308, 3366, 3388, 3393, 3403, 3428, 3467, 3498, 3525, 3568, 3574, 3575, 3576, 3577, 3626, 3649, 3654, 3668, 3688, 3717, 3758, 3786, 3828, 3891, 3910, 3915, 3928, 3948, 3992, 4018, 4047, 4088, 4151, 4171, 4176, 4188, 4208, 4247, 4283, 4292, 4308, 4353, 4411, 4432, 4448, 4473, 4497, 4543, 4568, 4613, 4671, 4693, 4698, 4708, 4733, 4772, 4803, 4829, 4873, 4931, 4953, 4958, 4959, 4968, 4993, 5027, 5063, 5090, 5133, 5191, 5214, 5219, 5233, 5253, 5277, 5323, 5352, 5393, 5456, 5476, 5481, 5493, 5513, 5552, 5583, 5612, 5658, 5716, 5737, 5742, 5753, 5773, 5807, 5848, 5873, 5918, 5976, 5997, 6013, 6038, 6082, 6108, 6133, 6178, 6236, 6258, 6263, 6273, 6298, 6332, 6368, 6395, 6438, 6478, 6479, 6496, 6519, 6524, 6538, 6558, 6587, 6628, 6656, 6698, 6761, 6780, 6785, 6798, 6818, 6862, 6888, 6917, 6958, 7021, 7041, 7046, 7058, 7078, 7112, 7148, 7177, 7223, 7281, 7302, 7307, 7318, 7338, 7367, 7413, 7438, 7483, 7541, 7563, 7568, 7578, 7603, 7642, 7673, 7699, 7743, 7801, 7823, 7828, 7838, 7863, 7892, 7933, 7960, 8003, 8061, 8070, 8084, 8089, 8103, 8123, 8167, 8193, 8221, 8263, 8326, 8345, 8350, 8363, 8383, 8422, 8453, 8482, 8528, 8586, 8607, 8612, 8623, 8643, 8677, 8718, 8743, 8788, 8846, 8867, 8883, 8908, 8947, 8978, 8993, 9003, 9048, 9106, 9128)

SP500 <- SP500[-SP500overlap,]
SP500$Kurs <- gsub(",", ".", SP500$Kurs )
SP500$Kurs <- as.numeric(SP500$Kurs)
SP500$Kurs <- SP500$Kurs/SP500$Kurs[1] * 100

# Calculating beta of the portfolio
beta <- cov(lowBetaPortfolio$kurs, SP500$Kurs)/var(SP500$Kurs)
```




```{r Portfolios since 1988 and 1996}

# reading and manipulating the data for the new time span
yield <- read_csv2("Yields.csv")
other_indices <- read.csv2("AndereIndices.csv")
pacific <- read.csv2("Pacific.csv")
gold <- read.csv2("Gold.csv")
gold <- na.omit(gold)
Nikkei <- read.csv2("Nikkei.csv")
pureValue <- read.csv2("purevalue.csv")
indices_isin <- read.csv2("Indizes.csv")
colnames(indices_isin) <- c("date", "WORLD", "EM", "FTSEDIV", "FTSEPER", "FTSE", "EURODIV", "EUROPER", "EURO", "NASDAQ", "SP500", "DAX", "SPSMALL600VALUE", "HANGSENGDIV", "HANGSENGPER", "HANGSENG", "SP500VALUE", "SP500GROWTH")
indices<- indices_isin[-c(1:4696),c(1, 2, 3, 6, 9, 10, 11, 12, 16, 17, 18)]
indices$Yield <- yield$Yield / 100
indices$dailyyield <- exp(log(1 + indices$Yield) / 365) - 1
indices$date <- as.Date(strptime(indices$date, format = "%d.%m.%y"))
indices$Year <- as.numeric(format(indices$date, "%Y"))
indices$Nikkei <- Nikkei[(nrow(Nikkei) - nrow(indices) + 1):nrow(Nikkei),2]

indices$cumYield <- rep( 0,nrow(indices))
indices$cumYield[1] <- 100
for(i in 2:nrow(indices)) {
  indices$cumYield[i] <- indices$cumYield[i - 1]*(1+indices$dailyyield[i-1])
}





cols_to_change <- c(4, 6, 7, 8, 9, 10, 11)

indices[,cols_to_change] <- apply(indices[,cols_to_change], 2, function(x) as.numeric(gsub(",", ".", x)))


# merging data frames and setting missing values to NA
indices <- merge(indices, lowBetaPortfolio, by = "date", all.x = TRUE)
colnames(indices)[which(colnames(indices) == "kurs")] <- "Low Beta"
std_prev <- sd(indices$`Low Beta`, na.rm = TRUE)
#replacing NAs with the last documented stock price
for(i in 1:nrow(indices)) {
  if(is.na(indices$`Low Beta`[i])) {
    indices$`Low Beta`[i] <- indices$`Low Beta`[i - 1]
  }
}
std_ratio <- 1 - sd(indices$`Low Beta`)/std_prev


SP <- indices[c(1,7)]
sp_value <- indices$SP500
SPmoving_avrg <- rep(TRUE, length(sp_value))
# Calculating S&P 200day moving average dates
for(i in 201 : length(sp_value)) {
  if(sp_value[i] < mean(sp_value[(i - 200):(i - 1)])) {
    SPmoving_avrg[i] <- FALSE
  }
}
# Initialize empty vectors
under <- c()
over <- c()

# Identify positions of first FALSE after TRUE and first TRUE after FALSE
for (i in 2:length(SPmoving_avrg)) {
  if (SPmoving_avrg[i] == FALSE && SPmoving_avrg[i-1] == TRUE) {
    under <- c(under, i)
  }
  if (SPmoving_avrg[i] == TRUE && SPmoving_avrg[i-1] == FALSE) {
    over <- c(over, i)
  }
}

SP_return <- SP
cSP <- SP
for(i in 1:nrow(SP)) {
  SP_return$SP500[i] <- (SP$SP500[i+ 1] - SP$SP500[i])/SP$SP500[i]
}
SP_return <- SP_return[-nrow(SP_return),]
SP_return$return3x <- SP_return$SP500*3
#### Gold under 200sma
gold$return <- c(rep(0, length(gold$X.NAME.)))
#calculating gold Returns 
for(i in 2:nrow(gold)) {
  gold$return[i] <- (gold$Gold.Bullion.LBM...t.oz.DELAY[i+ 1] - gold$Gold.Bullion.LBM...t.oz.DELAY[i])/gold$Gold.Bullion.LBM...t.oz.DELAY[i]
}
#adapting gold length
gold_1987 <- gold[-c(1:5216, nrow(gold)),]
for(i in 1:length(over)) {
  SP_return$return3x[under[i]:over[i]] <- gold_1987$return[under[i]:over[i]]
}
SP_return$return3x[under[length(under)]:nrow(SP_return)] <- gold_1987$return[under[length(under)]:nrow(SP_return)]

#creating the 3x leveraged portfolio for gold
SP_return<- SP_return[-1,]
SP <- rep(100, nrow(SP_return) + 1)
SP3x <- rep(100, nrow(SP_return) + 1)
for(i in 1:(nrow(SP_return))) {
  SP[i + 1] <- SP[i] * (1 + SP_return$SP500[i])
  SP3x[i + 1] <- SP3x[i] * (1 + SP_return$return3x[i])
}
indices$SP3xLev <- c(100, SP3x)
indices$Gold <- gold$Gold.Bullion.LBM...t.oz.DELAY[-c(1:5216)]



#### creating Cash under 200sma portfolio
cSP_return <- cSP

for(i in 1:nrow(cSP)) {
  cSP_return$SP500[i] <- (cSP$SP500[i+ 1] - cSP$SP500[i])/cSP$SP500[i]
}
cSP_return <- cSP_return[-nrow(cSP_return),]
cSP_return$return3x <- cSP_return$SP500*3
#adapting gold length
for(i in 1:length(over)) {
  cSP_return$return3x[under[i]:over[i]] <- 0
}
cSP_return$return3x[under[length(under)]:nrow(cSP_return)] <-0

#creating the 3x leveraged portfolio for cash
cSP_return <- cSP_return[-1,]
cSP <- rep(100, nrow(cSP_return) + 1)
cSP3x <- rep(100, nrow(cSP_return) + 1)
for(i in 1:(nrow(cSP_return))) {
  cSP[i + 1] <- cSP[i] * (1 + cSP_return$SP500[i])
  cSP3x[i + 1] <- cSP3x[i] * (1 + cSP_return$return3x[i])
}
indices$cSP3xLev <- c(100, cSP3x)

## Evolutionary Portfolio Theory
# cearing portfolio value
evo_stocks <- indices$WORLD/indices$WORLD[1]*100*0.87 + indices$EM/indices$EM[1]*100*0.13 
evo_fixedIncome <- indices$dailyyield
# Regimewechsel bestimmen
low20 <- c()
low40 <- c()
ath <- c()

for (i in 1:length(evo_stocks)) {
  if (evo_stocks[i] == max(evo_stocks[1:i])) {
    ath <- c(ath, i)
  }
  if (i > 1 && evo_stocks[i] < 0.8 * max(evo_stocks[1:(i-1)]) && all(evo_stocks[which(evo_stocks == evo_stocks[tail(ath, n = 1L)]) : (i - 1)] >= 0.8 * max(evo_stocks[1:(i-1)]))) {
    low20 <- c(low20, i)
  }
  if (i > 1 && evo_stocks[i] < 0.6 * max(evo_stocks[1:(i-1)]) && all(evo_stocks[which(evo_stocks == evo_stocks[tail(ath, n = 1L)]) : (i - 1)] >= 0.6 * max(evo_stocks[1:(i-1)]))) {
    low40 <- c(low40, i)
  }
}

low20  # positiones where the portfolio drops more than 20% for the first time before reaching a new all time high (ATH)
low40  # positiones where the portfolio drops more than 40% for the first time before reaching a new all time high
ath    # positiones where the portfolio reaches a new all time high for the first time after a crash

# identifying new ATHs after 20% drops
ath_store <- c()
for(i in 1:length(low20)) {
  ath_store <- c(ath_store, ath[which(sort(c(ath, low20)) == low20[i]) + 1])
}
evo_stock_returns <- rep(1, length(evo_stocks))
for (i in 1:(length(evo_stock_returns) - 1)) {
  evo_stock_returns[i] <-  (evo_stocks[i + 1] - evo_stocks[i])/evo_stocks[i]
}
evo_stock_returns[length(evo_stock_returns)] <- (evo_stocks[length(evo_stocks)]-evo_stocks[length(evo_stocks) - 1]) / evo_stocks[length(evo_stocks) - 1]
evo_portfolio <- c(100, rep(0, nrow(indices) - 1))

#function to apply different regimes
apply_returns <- function(start, end, regime, evo_portfolio) {
  if(regime == 1) {
    for(i in (start + 1) : end) {
      evo_portfolio[i] <- evo_portfolio[i - 1] * (1 + (evo_stock_returns[i]*0.8 + evo_fixedIncome[i] * 0.2))
    }
  }
  if(regime == 2) {
    for(i in (start + 1) : end) {
      evo_portfolio[i] <- evo_portfolio[i - 1] * (1 + evo_stock_returns[i])
    }
  }
  if(regime == 3) {
    for(i in (start + 1) : end) {
      evo_portfolio[i] <- evo_portfolio[i - 1] * (1 + (evo_stock_returns[i]*1.2 - evo_fixedIncome[i] * 0.2))
    }
  }
  return(evo_portfolio)
}


#applying functions manually on different regimes
evo_portfolio <- apply_returns(1, low20[1], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[1], ath_store[1], 2, evo_portfolio)
evo_portfolio <- apply_returns(ath_store[1], low20[2], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[2], ath_store[2], 2, evo_portfolio)
evo_portfolio <- apply_returns(ath_store[2], low20[3], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[3], low40[1], 2, evo_portfolio)
evo_portfolio <- apply_returns(low40[1], ath_store[3], 3, evo_portfolio)
evo_portfolio <- apply_returns(ath_store[3], low20[4], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[4], low40[2], 2, evo_portfolio)
evo_portfolio <- apply_returns(low40[2], ath_store[4], 3, evo_portfolio)
evo_portfolio <- apply_returns(ath_store[4], low20[5], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[5], ath_store[5], 2, evo_portfolio)
evo_portfolio <- apply_returns(ath_store[5], low20[6], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[6], ath_store[6], 2, evo_portfolio)
evo_portfolio <- apply_returns(ath_store[6], low20[7], 1, evo_portfolio)
evo_portfolio <- apply_returns(low20[6], length(evo_portfolio), 2, evo_portfolio)

#adding evoPortfolio to indices
indices$evoPortfolio <- evo_portfolio

## Yearly Returns

Indices_last_day <- indices %>%
  group_by(Year) %>%
  filter(date == max(date)) %>%
  ungroup()

Returns <- data.frame(Year = Indices_last_day$Year)

# looping over all columns except the year col
for (i in 2:ncol(Indices_last_day)) {
  col_name <- colnames(Indices_last_day)[i]  
  Returns[col_name] <- NA  #Creating Returns col where the returns will be displayed
  
  for (j in 2:nrow(Indices_last_day)) {
    current_year <- Indices_last_day$Year[j]  
    previous_year <- current_year - 1 
    
    current_price <- Indices_last_day[j, col_name]
    previous_price <- Indices_last_day[Indices_last_day$Year == previous_year, col_name]
    
    # storing the returns
    Returns[j, col_name] <- (current_price - previous_price) / previous_price
  }
}
Returns <- Returns[-1,]
Returns$Year <- c(1988:2022)

YearlyReturns1988 <- Returns[-c(1, 12, 13)]
YearlyReturns1996 <- Returns[-c(1:8), -c(12, 13, 15)]

## Monthly
# Monthly Returns
indices$Year <- as.numeric(format(indices$date, "%Y"))
indices$Month <- as.numeric(format(indices$date, "%m"))

Indices_last_day <- indices %>%
  group_by(Year, Month) %>%
  filter(date == max(date)) %>%
  ungroup()

# creating new data frame for the returns
Returns <- data.frame(Year = Indices_last_day$Year, Month = Indices_last_day$Month)


for (i in 2:ncol(Indices_last_day)) {
  col_name <- colnames(Indices_last_day)[i]  
  Returns[col_name] <- NA # Creating Returns col where the returns will be displayed
  
  for (j in 2:nrow(Indices_last_day)) {
    current_year <- Indices_last_day$Year[j]  
    current_month <- Indices_last_day$Month[j]  
    previous_year <- ifelse(current_month == 1, current_year - 1, current_year)  
    previous_month <- ifelse(current_month == 1, 12, current_month - 1)  
    
    current_price <- Indices_last_day[j, col_name]
    previous_price <- Indices_last_day[Indices_last_day$Year == previous_year & Indices_last_day$Month == previous_month, col_name]
    
    # Calculating Returns and storing them 
    Returns[j, col_name] <- (current_price - previous_price) / previous_price
  }
}

Returns <- Returns[-1,]
Returns$Year <- rep(1988:2022, each = 12)
Returns$Month <- c(1:12)


# sorting out the irrelevant cols
MonthlyReturns1988 <- Returns[c(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 17, 18, 19, 20, 21)]
MonthlyReturns1996 <- Returns[-c(1:(8*12)),c(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 17, 18, 19, 20, 21)]

#pureValue
pureValue <- na.omit(pureValue[-c(1 : (which(pureValue$X.NAME. == "29.12.95") - 1), (which(pureValue$X.NAME. == "02.01.23")) : length(pureValue$X.NAME.)),c(1,3)])
colnames(pureValue) <- c("date", "pureValue")
indices1996 <- cbind(indices[-c(1:(which(indices$date == "1996-01-01") - 1)),], pureValue$pureValue[-1])

#yearly
## yearly Returns
pureValue$date <- as.Date(pureValue$date, format = "%d.%m.%y")
pureValue$Year <- as.numeric(format(pureValue$date, "%Y"))

Indices_last_day <- pureValue %>%
  group_by(Year) %>%
  filter(date == max(date)) %>%
  ungroup()

# creating new df for returns
Returns <- data.frame(Year = Indices_last_day$Year)


for (i in 2:ncol(Indices_last_day)) {
  col_name <- colnames(Indices_last_day)[i]  
  Returns[col_name] <- NA  
  
  # Schleife über alle Jahre
  for (j in 2:nrow(Indices_last_day)) {
    current_year <- Indices_last_day$Year[j]  
    previous_year <- current_year - 1  
    
    current_price <- Indices_last_day[j, col_name]
    previous_price <- Indices_last_day[Indices_last_day$Year == previous_year, col_name]
    
    # storing returns
    Returns[j, col_name] <- (current_price - previous_price) / previous_price
  }
}
Returns <- Returns[-1,]
Returns$Year <- c(1996:2022)


YearlyReturns1996 <- cbind(YearlyReturns1996[-1], Returns[2])


## monthly Returns
#reading in pure value data
pureValue <- read.csv2("purevalue.csv")
pureValue <- na.omit(pureValue[-c(1 : (which(pureValue$X.NAME. == "29.12.95") - 1)),c(1,3)])
colnames(pureValue) <- c("date", "pureValue")
pureValue <- pureValue[c(1:which(pureValue$date == "30.12.22")),]
pureValue$date <- as.Date(pureValue$date, format = "%d.%m.%y")
pureValue$Year <- as.numeric(format(pureValue$date, "%Y"))
pureValue$Month <- as.numeric(format(pureValue$date, "%m"))

Indices_last_day <- pureValue %>%
  group_by(Year, Month) %>%
  filter(date == max(date)) %>%
  ungroup()

Returns <- data.frame(Year = Indices_last_day$Year, Month = Indices_last_day$Month)

for (i in 2:ncol(Indices_last_day)) {
  col_name <- colnames(Indices_last_day)[i]  
  Returns[col_name] <- NA 
  
  for (j in 2:nrow(Indices_last_day)) {
    current_year <- Indices_last_day$Year[j]  
    current_month <- Indices_last_day$Month[j] 
    previous_year <- ifelse(current_month == 1, current_year - 1, current_year) 
    previous_month <- ifelse(current_month == 1, 12, current_month - 1) 
    
    current_price <- Indices_last_day[j, col_name]
    previous_price <- Indices_last_day[Indices_last_day$Year == previous_year & Indices_last_day$Month == previous_month, col_name]
    
    # storing returns
    Returns[j, col_name] <- (current_price - previous_price) / previous_price
  }
}

Returns <- Returns[-1,]
Returns$Year <- rep(1996:2022, each = 12)
Returns$Month <- c(1:12)


MonthlyReturns1996 <- cbind(MonthlyReturns1996 , Returns$pureValue)
```

```{r Autocorrelation tests}
# collecting all time series that should be tested for autocorrelation
timeseries <- list(Monthly_Return_MSCI_World_1970 =  MonthlyReturns1970$World, Monthly_Return_SP_500 = MonthlyReturns1970$SP500, 
                   Monthly_Return_DAX_1970 = MonthlyReturns1970$DAX, Monthly_Return_HANG_SENG_1970 = MonthlyReturns1970$HANGSENG,
                   Monthly_Return_Nikkei_225_1970 = MonthlyReturns1970$Nikkei, Monthly_Return_Gold_1970 = MonthlyReturns1970$Gold,
                   Monthly_Return_SP500_Lev_Gold_1970 = MonthlyReturns1970$SP3xLev, Monthly_Return_SP500_Lev_Cash_1970 = YearlyReturns1970$cSP3xLev,
                   Yearly_Return_MSCI_World_1970 =  YearlyReturns1970$World, Yearly_Return_SP500_1970 = YearlyReturns1970$SP500, 
                   Yearly_Return_DAX_1970 = YearlyReturns1970$DAX, Yearly_Return_HANG_SENG_1970 = YearlyReturns1970$HANGSENG,
                   Yearly_Return_Nikkei_225_1970 = YearlyReturns1970$Nikkei, Yearly_Return_Gold_1970 = YearlyReturns1970$Gold,
                   Yearly_Return_SP500_Lev_Gold_1970 = YearlyReturns1970$SP3xLev, Yearly_Return_SP500_Lev_Cash_1970 = YearlyReturns1970$cSP3xLev,
                   Monthly_Return_MSCI_World_1988 = MonthlyReturns1988$WORLD, Monthly_Return_EM_1988 = MonthlyReturns1988$EM, 
                   Monthly_Return_FTSE_1988 = MonthlyReturns1988$FTSE, Monthly_Return_EURO_1988 = MonthlyReturns1988$EURO, 
                   Monthly_Return_NASDAQ_1988 = MonthlyReturns1988$NASDAQ, Monthly_Return_SP5001988 = MonthlyReturns1988$SP500,
                   Monthly_Return_DAX_1988 = MonthlyReturns1988$DAX, Monthly_Return_HANG_SENG_1988 = MonthlyReturns1988$HANGSENG,
                   Monthly_Return_SP500_Value_1988 = MonthlyReturns1988$SP500VALUE, Monthly_Return_SP500_Growth_1988 = MonthlyReturns1988$SP500GROWTH,
                   Monthly_Return_Nikkei_225_1988 = MonthlyReturns1988$Nikkei, Monthly_Return_Low_Beta_1988 = MonthlyReturns1988$`Low Beta`,
                   Monthly_Return_SP500_Lev_Gold_1988 = MonthlyReturns1988$SP3xLev,  Monthly_Return_Gold_1988 = MonthlyReturns1988$Gold,
                   Monthly_Return_SP500_Lev_Cash_1988 = MonthlyReturns1988$cSP3xLev, Monthly_Return_Evolutionary_Portfolio_1988 = MonthlyReturns1988$evoPortfolio,
                   Yearly_Return_MSCI_World_1988 = YearlyReturns1988$WORLD, Yearly_Return_EM_1988 = YearlyReturns1988$EM, 
                   Yearly_Return_FTSE_1988 = YearlyReturns1988$FTSE, Yearly_Return_EURO_1988 = YearlyReturns1988$EURO, 
                   Yearly_Return_NASDAQ_1988 = YearlyReturns1988$NASDAQ, Yearly_Return_SP5001988 = YearlyReturns1988$SP500,
                   Yearly_Return_DAX_1988 = YearlyReturns1988$DAX, Yearly_Return_HANG_SENG_1988 = YearlyReturns1988$HANGSENG,
                   Yearly_Return_SP500_Value_1988 = YearlyReturns1988$SP500VALUE, Yearly_Return_SP500_Growth_1988 = YearlyReturns1988$SP500GROWTH,
                   Yearly_Return_Nikkei_225_1988 = YearlyReturns1988$Nikkei, Yearly_Return_Low_Beta_1988 = YearlyReturns1988$`Low Beta`,
                   Yearly_Return_SP500_Lev_Gold_1988 = YearlyReturns1988$SP3xLev, Yearly_Return_Gold_1988 = YearlyReturns1988$Gold,
                   Yearly_Return_SP500_Lev_Cash_1988 = YearlyReturns1988$cSP3xLev, Yearly_Return_Evolutionary_Portfolio_1988 = YearlyReturns1988$evoPortfolio,
                   Monthly_Return_MSCI_World_1996 = MonthlyReturns1996$WORLD, Monthly_Return_EM_1996 = MonthlyReturns1996$EM, 
                   Monthly_Return_FTSE_1996 = MonthlyReturns1996$FTSE, Monthly_Return_EURO_1996 = MonthlyReturns1996$EURO, 
                   Monthly_Return_NASDAQ_1996 = MonthlyReturns1996$NASDAQ, Monthly_Return_SP5001996 = MonthlyReturns1996$SP500,
                   Monthly_Return_DAX_1996 = MonthlyReturns1996$DAX, Monthly_Return_HANG_SENG_1996 = MonthlyReturns1996$HANGSENG,
                   Monthly_Return_SP500_Value_1996 = MonthlyReturns1996$SP500VALUE, Monthly_Return_SP500_Growth_1996 = MonthlyReturns1996$SP500GROWTH,
                   Monthly_Return_Nikkei_225_1996 = MonthlyReturns1996$Nikkei, Monthly_Return_Low_Beta_1996 = MonthlyReturns1996$`Low Beta`,
                   Monthly_Return_SP500_Lev_Gold_1996 = MonthlyReturns1996$SP3xLev, Monthly_Return_Gold_1996 = MonthlyReturns1996$Gold,
                   Monthly_Return_SP500_Lev_Cash_1996 = MonthlyReturns1996$cSP3xLev, Monthly_Return_Evolutionary_Portfolio_1996 = MonthlyReturns1996$evoPortfolio, 
                   Monthly_Return_SP500_Small_Cap_Pure_Value_1996 = MonthlyReturns1996$`Returns$pureValue`, Yearly_Return_MSCI_World_1996 = YearlyReturns1996$WORLD, 
                   Yearly_Return_EM_1996 = YearlyReturns1996$EM, 
                   Yearly_Return_FTSE_1996 = YearlyReturns1996$FTSE, Yearly_Return_EURO_1996 = YearlyReturns1996$EURO, 
                   Yearly_Return_NASDAQ_1996 = YearlyReturns1996$NASDAQ, Yearly_Return_SP5001996 = YearlyReturns1996$SP500,
                   Yearly_Return_DAX_1996 = YearlyReturns1996$DAX, Yearly_Return_HANG_SENG_1996 = YearlyReturns1996$HANGSENG,
                   Yearly_Return_SP500_Value_1996 = YearlyReturns1996$SP500VALUE, Yearly_Return_SP500_Growth_1996 = YearlyReturns1996$SP500GROWTH,
                   Yearly_Return_Nikkei_225_1996 = YearlyReturns1996$Nikkei, Yearly_Return_Low_Beta_1996 = YearlyReturns1996$`Low Beta`,
                   Yearly_Return_SP500_Lev_Gold_1996 = YearlyReturns1996$SP3xLev, Yearly_Return_Gold_1996 = YearlyReturns1996$Gold,
                   Yearly_Return_SP500_Lev_Cash_1996 = YearlyReturns1996$cSP3xLev, Yearly_Return_Evolutionary_Portfolio_1996 = YearlyReturns1996$evoPortfolio, 
                   Yearly_Return_SP500_Small_Cap_Pure_Value_1996 = YearlyReturns1996$pureValue)

#Creating Dataframes for the results
ljung_box_results <- data.frame(Portfolio = character(), P.Value = numeric())
durbin_watson_results <- data.frame(Portfolio = character(), DW_Statistic = numeric(), P.Value = numeric())
for(i in seq_along(timeseries)) {
  ##Ljung-Box Test
  # Creating AR1 ARIMA Modell for
  model <- arima(timeseries[[i]], order = c(1, 0, 0)) 
  
  # Testing for the residuals and storing results
  ljung_box <- Box.test(model$residuals, lag = 5, type = "Ljung-Box")
  ljung_box_results <- rbind(ljung_box_results, c(names(timeseries[i]), ljung_box$p.value))
  
  ## Durbin Watson Test
  # Creating lagged portfolio return
  stock_prices_lag <- c(NA,timeseries[[i]][-length(timeseries[[i]])])
  
  # creating data frame with both time series
  df <- data.frame(timeseries[[i]], stock_prices_lag)
  
  # eliminating NAs
  df <- na.omit(df)
  
  # Regression
  model <- lm(timeseries[[i]][-1] ~ stock_prices_lag, data = df)
  
  # Storing results
  dw_result <- durbinWatsonTest(model)
  durbin_watson_results <- rbind(durbin_watson_results, c(names(timeseries[i]), round(as.numeric(dw_result$dw),3), round(as.numeric(dw_result$p), 4)))
}
#Renaming
colnames(ljung_box_results) <- c("Portfolio", "P-Value")
colnames(durbin_watson_results) <- c("Portfolio", "DW_Statistic","P-Value")
autocorr_results <- durbin_watson_results
autocorr_results$P_Value_Ljung_Box <-round(as.numeric(ljung_box_results$`P-Value`), 3)
```

```{r Autocorrelation tests}
# Creating Moving Block Bootstrap Function
mbb <- function(data, blockl){
  samples <- list()
  for (i in 1 : (nrow(data) - blockl + 1)) {
    samples[[i]] <- as.data.frame(data[c(i: (i + blockl - 1)),])
  }
  return(samples)
}

mbb_sampling <- function(data, blockl, samplenum) {
  samplesource <- mbb(data, blockl)
  blocknum <- floor(nrow(data)/blockl)
  bootstrapped_DFs <- list()
  for(i in 1:samplenum) {
    store_df <- as.data.frame(sample(samplesource, 1))
    for(j in 1 : blocknum) {
      store_df <- rbind(store_df, as.data.frame(sample(samplesource, 1)))
    }
    bootstrapped_DFs[[i]] <- store_df
  }
  return(bootstrapped_DFs)
}

samples10 <- mbb_sampling(YearlyReturns1996, 3, 10)
samples1000 <- mbb_sampling(YearlyReturns1996, 3, 1000)

##Crating the data frame with new means for 
#10 Samples
means_df <- data.frame(replicate(ncol(YearlyReturns1996), rep(0, length(samples10))))
names(means_df) <- names(YearlyReturns1996)

for(i in 1:length(samples10)) {
  for(j in 1:ncol(YearlyReturns1996)) {
    means_df[i, j] <- mean(samples10[[i]][[j]])
  }
}
samples10 <- means_df
#1000 samples
means_df <- data.frame(replicate(ncol(YearlyReturns1996), rep(0, length(samples1000))))
names(means_df) <- names(YearlyReturns1996)

for(i in 1:length(samples1000)) {
  for(j in 1:ncol(YearlyReturns1996)) {
    means_df[i, j] <- mean(samples1000[[i]][[j]])
  }
}
samples1000 <- means_df
```

```{r Visualizations}
###### finishing up the data sets
MonthlyReturns1970 <- MonthlyReturns1970[-1]
YearlyReturns1970 <- YearlyReturns1970[-1]
YearlyReturns1988 <- YearlyReturns1988[-12]
colnames(MonthlyReturns1970) <- c("MSCI World", "S&P 500", "DAX", "Hang Seng", "Nikkei 225", "Gold", "S&P 500 3x & Gold", "S&P 500 3x & Cash")
colnames(YearlyReturns1970) <- c("MSCI World", "S&P 500", "DAX", "Hang Seng", "Nikkei 225", "Gold", "S&P 500 3x & Gold", "S&P 500 3x & Cash")
colnames(MonthlyReturns1988) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", "Nikkei 225", "Low Beta","S&P 500 3x & Gold", "Gold", "S&P 500 3x + Cash", "Evolutionary Portfolio")
colnames(YearlyReturns1988) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", "Nikkei 225", "Low Beta","S&P 500 3x & Gold", "Gold", "S&P 500 3x + Cash", "Evolutionary Portfolio")  
colnames(YearlyReturns1996) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", "Nikkei 225", "Low Beta","S&P 500 3x & Gold", "Gold", "S&P 500 3x + Cash", "Evolutionary Portfolio", "S&P Small Cap Pure Value")  
colnames(YearlyReturns1996) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", "Nikkei 225", "Low Beta","S&P 500 3x & Gold", "Gold", "S&P 500 3x + Cash", "Evolutionary Portfolio", "S&P Small Cap Pure Value")  


#Functions for the confidence sets
marg_CI <- function(Returns, title, conflevel) {
  return_estimates_transposed <- data.frame(mean=unlist(lapply(Returns, mean)), variance = diag(cov(Returns)/nrow(Returns)))
  return_estimates_transposed <- cbind(jurisdiction = rownames(return_estimates_transposed), return_estimates_transposed)
  rownames(return_estimates_transposed) <- NULL
  irank(return_estimates_transposed$mean)
  
  return_cov_mat <- diag(return_estimates_transposed$variance^2)
  CS_marg <- csranks(return_estimates_transposed$mean, cov(Returns)/nrow(Returns), coverage=conflevel, simul=FALSE, R=1000, seed=101)
  return_rankL_marg <- CS_marg$L
  return_rankU_marg <- CS_marg$U
  
  grid::current.viewport()
  
  plotmarg <- plot(CS_marg, popnames = return_estimates_transposed$jurisdiction, title = title, 
                   subtitle = "(with 5% marginal confidence sets)", colorbins=4)
  return(plotmarg)
}

sim_CI <- function(Returns, title, conflevel) {
  return_estimates_transposed <- data.frame(mean=unlist(lapply(Returns, mean)), variance = diag(cov(Returns) / nrow(Returns)))
  return_estimates_transposed <- cbind(jurisdiction = rownames(return_estimates_transposed), return_estimates_transposed)
  rownames(return_estimates_transposed) <- NULL
  irank(return_estimates_transposed$mean)
  return_cov_mat <- diag(return_estimates_transposed$variance^2)
  CS_simul <- csranks(return_estimates_transposed$mean, cov(Returns)/nrow(Returns), coverage=conflevel, simul=TRUE, R=1000, seed=101)
  math_rankL_simul <- CS_simul$L
  math_rankU_simul <- CS_simul$U
  grid::current.viewport()
  plotsimul <- plot(CS_simul, popnames = return_estimates_transposed$jurisdiction, title=title, 
                    subtitle="(with 5% simultaneous confidence sets)", colorbins=4)
  return(plotsimul)
}

###########
#1970

plot1970 <- data.frame(
  x = indices70$date,
  y1 = indices70$World,
  y2 = indices70$SP500,
  y3 = indices70$DAX,
  y4 = indices70$HANGSENG,
  y5 = indices70$Nikkei,
  y6 = indices70$Gold,
  y7 = indices70$SP3xLev,
  y8 = indices70$cSP3xLev
)

# Leveraged Portfolios vs. S&P 500

ggplot(plot1970, aes(x = x)) +
  geom_line(aes(y = y2, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y7, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y8, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "S&P 500 3x & Gold/Cash vs. S&P 500 1970 - 2022") +
  scale_y_continuous(trans = "log10", breaks = c(100, 1000, 10000, 100000, 1000000, 3000000), 
                     labels = c("100", "1,000", "10,000", "100,000", "1,000,000", "3,000,000")) +
  
  scale_color_manual(
    values = c("Graph 1" = "green", "Graph 2" = "blue", "Graph 3" = "pink"),
    labels = c("S&P 500", "S&P 500 3x & Gold", "S&P 500 3x & Cash")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

#All
ggplot(plot1970, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y4, color = "Graph 4"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y5, color = "Graph 5"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y6, color = "Graph 6"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y7, color = "Graph 7"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y8, color = "Graph 8"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Portfolios since 1970") +
  scale_y_continuous(trans = "log10", breaks = c(100, 1000, 10000, 100000, 1000000, 3000000), 
                     labels = c("100", "1,000", "10,000", "100,000", "1,000,000", "3,000,000")) +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "red", "Graph 3" = "green", "Graph 4" = "orange", "Graph 5" = "pink", "Graph 6" = "yellow", "Graph 7" = "black", "Graph 8" = "turquoise"),
    labels = c("MSCI World", "S&P 500", "DAX", "Hang Seng", "Nikkei 225", "Gold", "S&P 500 3x & Gold", "S&P 500 3x & Cash")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

# Avrg performance and standard deviation bar charts
## Yearly 
#Mcalculating means
year1970mean <- colMeans(YearlyReturns1970)
names(year1970mean) <- c("MSCI World", "S&P 500", "DAX", "Hang Seng", "Nikkei 225", "Gold", "S&P 500 3x & Gold", "S&P 500 3x & Cash")
# creating the data frame
year1970data <- data.frame(Kategorie = paste0("Portfolio ", 1:8), Mittelwert = year1970mean)
# calculating sd
year1970sd <- colSds(as.matrix(YearlyReturns1970))
year1970data$sd <- year1970sd
# plotting bar plots
ggplot(year1970data, aes(x = Kategorie, y = Mittelwert)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Average Return", title = "Yearly Average Portfolio Returns") +
  theme_minimal()+
  scale_x_discrete(labels = names(year1970mean))

ggplot(year1970data, aes(x = Kategorie, y = sd)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Standard Deviation", title = "Standard Deviation of Yearly Portfolio Returns") +
  theme_minimal()+
  scale_x_discrete(labels = names(year1970sd))

## Monthly 
month1970mean <- colMeans(MonthlyReturns1970)
names(month1970mean) <- c("MSCI World", "S&P 500", "DAX", "Hang Seng", "Nikkei 225", "Gold", "S&P 500 3x & Gold", "S&P 500 3x & Cash")
month1970data <- data.frame(Kategorie = paste0("Portfolio ", 1:8), Mittelwert = month1970mean)
month1970sd <- colSds(as.matrix(MonthlyReturns1970))
month1970data$sd <- month1970sd
ggplot(month1970data, aes(x = Kategorie, y = Mittelwert)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Average Returns", title = "Monthly Average Portfolio Returns") +
  theme_minimal()+
  scale_x_discrete(labels = names(month1970mean))

ggplot(month1970data, aes(x = Kategorie, y = sd)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Standard Deviations", title = "Standard Deviations of Monthly Portfolio Returns") +
  theme_minimal()+
  scale_x_discrete(labels = names(month1970sd))


# 1988
plot_indices <- indices
for(i in 2:ncol(indices)) {
  plot_indices[i] <- plot_indices[i] / plot_indices[1, i]*100
}
plot1988 <- data.frame(
  x = plot_indices$date,
  y1 = plot_indices$WORLD,
  y2 = plot_indices$EM,
  y3 = plot_indices$FTSE,
  y4 = plot_indices$EURO,
  y5 = plot_indices$NASDAQ,
  y6 = plot_indices$SP500,
  y7 = plot_indices$DAX,
  y8 = plot_indices$SP500VALUE,
  y9 = plot_indices$SP500GROWTH,
  y10 = plot_indices$HANGSENG,
  y11 = plot_indices$Nikkei,
  y12 = plot_indices$Gold,
  y13 = plot_indices$SP3xLev,
  y14 = plot_indices$cumYield,
  y15 = plot_indices$evoPortfolio,
  y16 = plot_indices$`Low Beta`
)


#low beta
ggplot(plot1988, aes(x = x)) +
  geom_line(aes(y = y16, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Low Beta vs. S&P 500 1988 - 2022") +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "green"),
    labels = c("Low Beta", "S&P 500")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

# Evolutionary Portfolio

ggplot(plot1988, aes(x = x)) +
  geom_line(aes(y = y15, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Evolutionary Portfolio vs. S&P 500 1988 - 2022") +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "green"),
    labels = c("Evolutionary Portfolio", "S&P 500")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

plot1988indices <- data.frame(
  x = plot_indices$date,
  y1 = plot_indices$WORLD,
  y2 = plot_indices$EM,
  y3 = plot_indices$FTSE,
  y4 = plot_indices$EURO,
  y5 = plot_indices$NASDAQ,
  y6 = plot_indices$SP500,
  y7 = plot_indices$DAX,
  y8 = plot_indices$HANGSENG,
  y9 = plot_indices$Nikkei
)

ggplot(plot1988indices, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y4, color = "Graph 4"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y5, color = "Graph 5"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y6, color = "Graph 6"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y7, color = "Graph 7"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y8, color = "Graph 8"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y9, color = "Graph 9"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Index Portfolios since 1988") +
  scale_y_continuous(trans = "log10", breaks = c(50, 100, 500, 1000, 5000), 
                     labels = c("50", "100", "500", "1,000", "5,000")) +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "red", "Graph 3" = "green", "Graph 4" = "orange",
               "Graph 5" = "pink", "Graph 6" = "yellow", "Graph 7" = "black",
               "Graph 8" = "cyan", "Graph 9" = "magenta"),
    labels = c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", "S&P 500", "DAX", "Hang Seng", "Nikkei 225")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

plot1988SPs <- data.frame(
  x = plot_indices$date,
  y1 = plot_indices$SP500,
  y2 = plot_indices$SP500VALUE,
  y3 = plot_indices$SP500GROWTH
)

ggplot(plot1988SPs, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Factor Portfolios since 1988") +
  scale_y_continuous(trans = "log10", breaks = c(100, 300, 1000, 3000), 
                     labels = c("100", "300", "1,000", "3,000")) +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "red", "Graph 3" = "green"),
    labels = c("S&P 500", "S&P 500 Value", "S&P 500 Growth")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

plot1988others <- data.frame(
  x = plot_indices$date,
  y1 = plot_indices$SP500,
  y2 = plot_indices$evoPortfolio,
  y3 = plot_indices$SP3xLev,
  y4 = plot_indices$Gold,
  y5 = plot_indices$cSP3xLev,
  y6 =  plot_indices$`Low Beta`
)
ggplot(plot1988others, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y4, color = "Graph 4"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y5, color = "Graph 5"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y6, color = "Graph 6"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Other Portfolios since 1988") +
  scale_y_continuous(trans = "log10", breaks = c(50, 100, 1000, 10000, 100000), 
                     labels = c("50", "100","1,000", "10,000", "100,000")) +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "red", "Graph 3" = "green", "Graph 4" = "orange",
               "Graph 5" = "pink", "Graph 6" = "yellow"),
    labels = c("S&P 500", "Evolutionary Portfolio", "S&P 500 3x & Gold", "Gold", "S&P 500 3x + Cash", "Low Beta")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

# Average performance bar chart
## Yearly 
yearly_mean_values1988 <- colMeans(YearlyReturns1988)  
names(yearly_mean_values1988) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", 
             "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", 
             "Nikkei 225", "Low Beta", "S&P 500 3x & Gold", "Gold", "S&P 500 3x & Cash", 
             "Evolutionary Portfolio")

mean_df <- data.frame(
  Variable = names(yearly_mean_values1988),
  Mean = yearly_mean_values1988
)
yearly_sd_values1988 <- colSds(as.matrix(YearlyReturns1988))
mean_df$sd <- yearly_sd_values1988
# Creating Bar charts
#average Returns
ggplot(mean_df, aes(x = Variable, y = Mean)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Average Returns", title = "Yearly Average Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
# sd
ggplot(mean_df, aes(x = Variable, y = sd)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Standard Deviations", title = "Standard Deviations of Yearly Portfolio Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

## Monthly 
monthly_mean_values1988 <- colMeans(MonthlyReturns1988)
names(monthly_mean_values1988) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe","Nasdaq-100", "NASDAQ-100", 
                                   "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", 
                                   "Nikkei 225", "S&P 500 3x & Gold", "Gold", "S&P 500 3x & Cash", 
                                   "Evolutionary Portfolio")

monthly_mean_df1988 <- data.frame(
  Variable = names(monthly_mean_values1988),
  Mean = monthly_mean_values1988
)
# sd
monthly_sd_values1988 <- colSds(as.matrix(MonthlyReturns1988))
monthly_mean_df1988$sd <- monthly_sd_values1988
# Creating Bar charts
# average Returns
ggplot(monthly_mean_df1988, aes(x = Variable, y = Mean)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Average Returns", title = "Monthly Average Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#sd
ggplot(monthly_mean_df1988, aes(x = Variable, y = sd)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Standard Deviations", title = "Standard Deviations of Monthly Portfolio Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# 1996
#adding graph with pure value

plot_indices1996 <- indices1996
for(i in 2:ncol(plot_indices1996)) {
  plot_indices1996[i] <- plot_indices1996[i] / plot_indices1996[1, i]*100
}
plot1996 <- data.frame(
  x = plot_indices1996$date,
  y1 = plot_indices1996$WORLD,
  y2 = plot_indices1996$EM,
  y3 = plot_indices1996$FTSE,
  y4 = plot_indices1996$EURO,
  y5 = plot_indices1996$NASDAQ,
  y6 = plot_indices1996$SP500,
  y7 = plot_indices1996$DAX,
  y8 = plot_indices1996$SP500VALUE,
  y9 = plot_indices1996$SP500GROWTH,
  y10 = plot_indices1996$HANGSENG,
  y11 = plot_indices1996$Nikkei,
  y12 = plot_indices1996$Gold,
  y13 = plot_indices1996$SP3xLev,
  y14 = plot_indices1996$evoPortfolio,
  y15 = plot_indices1996$cumYield,
  y16 = plot_indices1996$`pureValue$pureValue[-1]`
)

plot1996indices <- data.frame(
  x = plot_indices1996$date,
  y1 = plot_indices1996$WORLD,
  y2 = plot_indices1996$EM,
  y3 = plot_indices1996$FTSE,
  y4 = plot_indices1996$EURO,
  y5 = plot_indices1996$NASDAQ,
  y6 = plot_indices1996$SP500,
  y7 = plot_indices1996$DAX,
  y8 = plot_indices1996$HANGSENG,
  y9 = plot_indices1996$Nikkei
)


ggplot(plot1996indices, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y4, color = "Graph 4"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y5, color = "Graph 5"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y6, color = "Graph 6"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y7, color = "Graph 7"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y8, color = "Graph 8"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y9, color = "Graph 9"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Index Portfolios since 1996") +
  scale_y_continuous(trans = "log10", breaks = c(30, 100, 300, 1000, 3000, 10000), 
                     labels = c("30", "100", "300", "1000", "3000", "10000")) +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "red", "Graph 3" = "green", "Graph 4" = "orange",
               "Graph 5" = "pink", "Graph 6" = "yellow", "Graph 7" = "black",
               "Graph 8" = "cyan", "Graph 9" = "magenta"),
    labels = c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", "SP 500", "DAX", "Hang Seng", "Nikkei 225")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()


plot1996SPs <- data.frame(
  x = plot_indices1996$date,
  y1 = plot_indices1996$SP500,
  y2 = plot_indices1996$SP500VALUE,
  y3 = plot_indices1996$SP500GROWTH,
  y4 = plot_indices1996$`pureValue$pureValue[-1]`
)


ggplot(plot1996SPs, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y4, color = "Graph 4"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Factor Portfolios since 1996") +
  scale_y_continuous(trans = "log10", breaks = c(50, 100, 300, 1000), 
                     labels = c("50", "100", "300", "1000")) +
  scale_color_manual(
    values = c("Graph 1" = "yellow", "Graph 2" = "red", "Graph 3" = "green", "Graph 4" = "blue"),
    labels = c("S&P 500", "S&P 500 Value", "S&P 500 Growth", "S&P Small Cap Pure Value")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()

plot1996other <- data.frame(
  x = plot_indices1996$date,
  y1 = plot_indices1996$SP500,
  y2 = plot_indices1996$evoPortfolio,
  y3 = plot_indices1996$SP3xLev,
  y4 = plot_indices1996$Gold,
  y5 = plot_indices1996$cSP3xLev
)
ggplot(plot1996other, aes(x = x)) +
  geom_line(aes(y = y1, color = "Graph 1"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y2, color = "Graph 2"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y3, color = "Graph 3"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y4, color = "Graph 4"), linetype = "solid", linewidth = 1) +
  geom_line(aes(y = y5, color = "Graph 5"), linetype = "solid", linewidth = 1) +
  labs(x = "Year", y = "Portfolio Value", title = "Other Portfolios since 1996") +
  scale_y_continuous(trans = "log10", breaks = c(50, 100, 300, 1000, 3000, 10000), 
                     labels = c("50", "100", "300", "1000", "3000",  "10000")) +
  scale_color_manual(
    values = c("Graph 1" = "blue", "Graph 2" = "red", "Graph 3" = "green", "Graph 4" = "orange",
               "Graph 5" = "pink", "Graph 6" = "yellow"),
    labels = c("S&P 500",  "Evolutionary Portfolio", "S&P 500 3x + Gold", "Gold", "S&P 500 3x + Cash")
  ) +
  guides(color = guide_legend(title = "Portfolios"))+
  theme_minimal()


# Average performance bar chart
## Yearly 

yearly_mean_values1996 <- colMeans(YearlyReturns1996)  
names(yearly_mean_values1996) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", 
                                   "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", 
                                   "Nikkei 225", "Low Beta", "S&P 500 3x & Gold", "Gold", "S&P 500 3x & Cash", 
                                   "Evolutionary Portfolio", "S&P Small Cap Pure Value")


mean_df1996 <- data.frame(
  Variable = names(yearly_mean_values1996),
  Mean = yearly_mean_values1996
)
#sd
yearly_sd_values1996 <- colSds(as.matrix(YearlyReturns1996))
mean_df1996$sd <- yearly_sd_values1996
# Creating Bar charts
#avrg Returns
ggplot(mean_df1996, aes(x = Variable, y = Mean)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Average Returns", title = "Yearly Average Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#sd
ggplot(mean_df1996, aes(x = Variable, y = sd)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Standard Deviations", title = "Standard Deviations of Yearly Portfolio Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

## Monthly 

monthly_mean_values1996 <- colMeans(MonthlyReturns1996)
names(monthly_mean_values1996) <- c("MSCI World", "MSCI EM", "FTSE 100", "MSCI Europe", "NASDAQ-100", 
                                    "S&P 500", "DAX", "Hang Seng", "S&P 500 Value", "S&P 500 Growth", 
                                    "Nikkei 225", "Low Beta", "S&P 500 3x & Gold", "Gold", "S&P 500 3x & Cash", 
                                    "Evolutionary Portfolio", "S&P Small Cap Pure Value")

monthly_mean_df1996 <- data.frame(
  Variable = names(monthly_mean_values1996),
  Mean = monthly_mean_values1996
)
#sd
monthly_sd_values1996 <- colSds(as.matrix(MonthlyReturns1996))
monthly_mean_df1996$sd <- monthly_sd_values1996
# Creating Bar charts
#avrg Returns
ggplot(monthly_mean_df1996, aes(x = Variable, y = Mean)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Average Returns", title = "Monthly Average Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#sd
ggplot(monthly_mean_df1996, aes(x = Variable, y = sd)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Standard Deviations", title = "Standard Deviations of Yearly Portfolio Returns") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))





#######
##Sharp Ratios
#1970
year1970data$sharp <- year1970data$Mittelwert / year1970data$sd
month1970data$sharp <-month1970data$Mittelwert / month1970data$sd


ggplot(year1970data, aes(x = rownames(year1970data), y = sharp)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Sharp Ratio", title = "Sharp Ratios of Yearly Returns since 1970") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(month1970data, aes(x = rownames(month1970data), y = sharp)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Sharp Ratio", title = "Sharp Ratios of Monthly Returns since 1970") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


#1988
mean_df$sharp <- mean_df$Mean / mean_df$sd
monthly_mean_df1988$sharp <- monthly_mean_df1988$Mean / monthly_mean_df1988$sd


ggplot(mean_df, aes(x = Variable, y = sharp)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Sharp Ratio", title = "Sharp Ratios of Yearly Returns since 1988") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(monthly_mean_df1988, aes(x = Variable, y = sharp)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Sharp Ratio", title = "Sharp Ratios of Monthly Returns since 1988") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


#1996
mean_df1996$sharp <- mean_df1996$Mean / mean_df1996$sd
monthly_mean_df1996$sharp <- monthly_mean_df1996$Mean /monthly_mean_df1996$sd


ggplot(mean_df1996, aes(x = Variable, y = sharp)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Sharp Ratio", title = "Sharp Ratios of Yearly Returns since 1996") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(monthly_mean_df1996, aes(x = Variable, y = sharp)) +
  geom_bar(stat = "identity", fill = "darkgrey") +
  labs(x = "Portfolios", y = "Sharp Ratio", title = "Sharp Ratios of Monthly Returns since 1996") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))




### Rankings
## Bootstrap rankings
ranking10samples <- marg_CI(samples10, "Ranking with 10 Resampling Iterations", 0.95)
ranking1000samples <- marg_CI(samples1000, "Ranking with 1000 Resampling Iterations", 0.95)
grid.arrange(ranking10samples, ranking1000samples, ncol = 2)

## Rankings 1970 0.95
# Monthly
marg1970monthlyCI95 <- marg_CI(MonthlyReturns1970, "Ranking of avrg. Monthly Returns since 1970 with marg. CI", 0.95)
sim1970monthlyCI95 <- sim_CI(MonthlyReturns1970, "Ranking of avrg. Monthly Returns since 1970 with sim. CI", 0.95)
grid.arrange(marg1970monthlyCI95, sim1970monthlyCI95, ncol = 2)
# Yearly
marg1970yearlyCI95 <- marg_CI(YearlyReturns1970, "Ranking of avrg. Yearly Returns since 1970 with marg. CI", 0.95)
sim1970yearlyCI95 <- sim_CI(YearlyReturns1970, "Ranking of avrg. Yearly Returns since 1970 with sim. CI", 0.95)
grid.arrange(marg1970yearlyCI95, sim1970yearlyCI95, ncol = 2)

## Rankings 1988 0.95
# Monthly
marg1988monthlyCI95 <- marg_CI(MonthlyReturns1988, "Ranking of avrg. Monthly Returns since 1988 with marg. CI", 0.95)
sim1988monthlyCI95 <- sim_CI(MonthlyReturns1988, "Ranking of avrg. Monthly Returns since 1988 with sim. CI", 0.95)
grid.arrange(marg1988monthlyCI95, sim1988monthlyCI95, ncol = 2)
# Yearly
marg1988yearlyCI95 <- marg_CI(YearlyReturns1988, "Ranking of avrg. Yearly Returns since 1988 with marg. CI", 0.95)
sim1988yearlyCI95 <- sim_CI(YearlyReturns1988, "Ranking of avrg. Yearly Returns since 1988 with sim. CI", 0.95)
grid.arrange(marg1988yearlyCI95, sim1988yearlyCI95, ncol = 2)

## Rankings 1996 0.95
# Monthly
marg1996monthlyCI95 <- marg_CI(MonthlyReturns1996, "Ranking of avrg. Monthly Returns since 1996 with marg. CI", 0.95)
sim1996monthlyCI95 <- sim_CI(MonthlyReturns1996, "Ranking of avrg. Monthly Returns since 1996 with sim. CI", 0.95)
grid.arrange(marg1996monthlyCI95, sim1996monthlyCI95, ncol = 2)
# Yearly
marg1996yearlyCI95 <- marg_CI(YearlyReturns1996, "Ranking of avrg. Yearly Returns since 1996 with marg. CI", 0.95)
sim1996yearlyCI95 <- sim_CI(YearlyReturns1996, "Ranking of avrg. Yearly Returns since 1996 with sim. CI", 0.95)
grid.arrange(marg1996yearlyCI95, sim1996yearlyCI95, ncol = 2)

## Rankings 1970 0.5
# Monthly
marg1970monthlyCI50 <- marg_CI(MonthlyReturns1970, "Ranking of avrg. Monthly Returns since 1970 with marg. CI", 0.5)
sim1970monthlyCI50 <- sim_CI(MonthlyReturns1970, "Ranking of avrg. Monthly Returns since 1970 with sim. CI", 0.5)
grid.arrange(marg1970monthlyCI50, sim1970monthlyCI50, ncol = 2)
# Yearly
marg1970yearlyCI50 <- marg_CI(YearlyReturns1970, "Ranking of avrg. Yearly Returns since 1970 with marg. CI", 0.5)
sim1970yearlyCI50 <- sim_CI(YearlyReturns1970, "Ranking of avrg. Yearly Returns since 1970 with sim. CI", 0.5)
grid.arrange(marg1970yearlyCI50, sim1970yearlyCI50, ncol = 2)

## Rankings 1988 0.5
# Monthly
marg1988monthlyCI50 <- marg_CI(MonthlyReturns1988, "Ranking of avrg. Monthly Returns since 1988 with marg. CI", 0.5)
sim1988monthlyCI50 <- sim_CI(MonthlyReturns1988, "Ranking of avrg. Monthly Returns since 1988 with sim. CI", 0.5)
grid.arrange(marg1988monthlyCI50, sim1988monthlyCI50, ncol = 2)
# Yearly
marg1988yearlyCI50 <- marg_CI(YearlyReturns1988, "Ranking of avrg. Yearly Returns since 1988 with marg. CI", 0.5)
sim1988yearlyCI50 <- sim_CI(YearlyReturns1988, "Ranking of avrg. Yearly Returns since 1988 with sim. CI", 0.5)
grid.arrange(marg1988yearlyCI50, sim1988yearlyCI50, ncol = 2)

## Rankings 1996 0.5
# Monthly
marg1996monthlyCI50 <- marg_CI(MonthlyReturns1996, "Ranking of avrg. Monthly Returns since 1996 with marg. CI", 0.5)
sim1996monthlyCI50 <- sim_CI(MonthlyReturns1996, "Ranking of avrg. Monthly Returns since 1996 with sim. CI", 0.5)
grid.arrange(marg1996monthlyCI50, sim1996monthlyCI50, ncol = 2)
# Yearly
marg1996yearlyCI50 <- marg_CI(YearlyReturns1996, "Ranking of avrg. Yearly Returns since 1996 with marg. CI", 0.5)
sim1996yearlyCI50 <- sim_CI(YearlyReturns1996, "Ranking of avrg. Yearly Returns since 1996 with sim. CI", 0.5)
grid.arrange(marg1996yearlyCI50, sim1996yearlyCI50, ncol = 2)

## Rankings 1970 0.05
# Monthly
marg1970monthlyCI05 <- marg_CI(MonthlyReturns1970, "Ranking of avrg. Monthly Returns since 1970 with marg. CI", 0.05)
sim1970monthlyCI05 <- sim_CI(MonthlyReturns1970, "Ranking of avrg. Monthly Returns since 1970 with sim. CI", 0.05)
grid.arrange(marg1970monthlyCI05, sim1970monthlyCI05, ncol = 2)
# Yearly
marg1970yearlyCI05 <- marg_CI(YearlyReturns1970, "Ranking of avrg. Yearly Returns since 1970 with marg. CI", 0.05)
sim1970yearlyCI05 <- sim_CI(YearlyReturns1970, "Ranking of avrg. Yearly Returns since 1970 with sim. CI", 0.05)
grid.arrange(marg1970yearlyCI05, sim1970yearlyCI05, ncol = 2)

## Rankings 1988 0.05
# Monthly
marg1988monthlyCI05 <- marg_CI(MonthlyReturns1988, "Ranking of avrg. Monthly Returns since 1988 with marg. CI", 0.05)
sim1988monthlyCI05 <- sim_CI(MonthlyReturns1988, "Ranking of avrg. Monthly Returns since 1988 with sim. CI", 0.05)
grid.arrange(marg1988monthlyCI05, sim1988monthlyCI05, ncol = 2)
# Yearly
marg1988yearlyCI05 <- marg_CI(YearlyReturns1988, "Ranking of avrg. Yearly Returns since 1988 with marg. CI", 0.05)
sim1988yearlyCI05 <- sim_CI(YearlyReturns1988, "Ranking of avrg. Yearly Returns since 1988 with sim. CI", 0.05)
grid.arrange(marg1988yearlyCI05, sim1988yearlyCI05, ncol = 2)

## Rankings 1996 0.05
# Monthly
marg1996monthlyCI05 <- marg_CI(MonthlyReturns1996, "Ranking of avrg. Monthly Returns since 1996 with marg. CI", 0.05)
sim1996monthlyCI05 <- sim_CI(MonthlyReturns1996, "Ranking of avrg. Monthly Returns since 1996 with sim. CI", 0.05)
grid.arrange(marg1996monthlyCI05, sim1996monthlyCI05, ncol = 2)
# Yearly
marg1996yearlyCI05 <- marg_CI(YearlyReturns1996, "Ranking of avrg. Yearly Returns since 1996 with marg. CI", 0.05)
sim1996yearlyCI05 <- sim_CI(YearlyReturns1996, "Ranking of avrg. Yearly Returns since 1996 with sim. CI", 0.05)
grid.arrange(marg1996yearlyCI05, sim1996yearlyCI05, ncol = 2)

```



